name: .NET Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Web API image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest ./api
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest

      - name: Build and push Client image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest ./cicdpractice
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/webapp:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/client:latest
            docker-compose up -d
